#include "Game_Data.h"
#include <stddef.h>





const uint8_t map_data_level1[MAP_HEIGHT][MAP_WIDTH] = 
{
    {TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_FIRE, TILE_TYPE_NORMAL, TILE_TYPE_ICE, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_NORMAL, TILE_TYPE_EXIT, TILE_TYPE_WALL},
    {TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL, TILE_TYPE_WALL}
};

// Define your game levels
const Level_t game_levels[] = {
    {
        .id = 1,
        .map_data = map_data_level1, // Pointer to the actual map data
        .player1_start = { .x = 2.0f, .y = 2.0f}, // Ice Person start
        .player2_start = { .x = 4.0f, .y = 2.0f }, // Fire Person start
        .time_limit_sec = 120 // 2 minutes
    },
    // Add more levels here:
    // {
    //     .id = 2,
    //     .map_data = map_data_level2, // Assuming map_data_level2 is defined elsewhere
    //     .player1_start = { .x = 1, .y = 1 },
    //     .player2_start = { .x = 2, .y = 2 },
    //     .time_limit_sec = 180
    // },
};

// Calculate the number of game levels
const uint8_t NUM_GAME_LEVELS = sizeof(game_levels) / sizeof(game_levels[0]);

// Function to get a level by its ID
const Level_t* Level_GetById(uint8_t level_id) {
    if (level_id > 0 && level_id <= NUM_GAME_LEVELS) {
        return &game_levels[level_id - 1]; // Level IDs are 1-based
    }
    return NULL; // Level not found
}
